### PR TITLE
Fix Bugs for age and past date

### LINKED ISSUE #129: [PE-D][Tester A] Add person bug
I am unable to add a person even after adding the specified command parameters. Also, hard to undertsand where i'm going wrong because of no error message to display what the issue is. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: D-Limiter/ped#1

### LINKED ISSUE #157: [PE-D][Tester A] view on date bug
When i type in a gibberish date, like for example, 01-01-0001, i get the slots for both that date and the date for 31 December. Perhaps would be benficial to check for date related bugs in most commands to avoid unexcpected issues on runtime.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: D-Limiter/ped#5

### PR DESCRIPTION
**Pull request by wj331**
1. Fix bug when age entered is not an integer
2. Fix bug when view does not throw an error if date has already passed
3. Minor code restructuring

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewAvailableCommandParser.java [hunk 1]
```diff
@@ -76,10 +67,37 @@ public ViewAvailableCommand parse(String args) throws ParseException {
                         + ViewAvailableCommand.MESSAGE_USAGE);
             }
 
+            if (isPastDate(date)) {
+                throw new ParseException(MESSAGE_PAST_DATE + "\n" + "Please insert in the following format: " + "\n"
+                        + ViewAvailableCommand.MESSAGE_USAGE);
```
Comment (simbayippy) [inline src/main/java/seedu/address/logic/parser/ViewAvailableCommandParser.java]: error thrown can just be MESSAGE_PAST_DATE with a bit more details

e.g. Date entered has past already! Date must be after current date 

should be sufficient, instead of including message usage. Also, could you de-capitalise DATE to just Date for the relevant errors

follows as per other errors thrown

**Review by simbayippy — DISMISSED** [review]
minor details, just a change in error format and it'll be good

File: src/main/java/seedu/address/logic/parser/ViewAvailableCommandParser.java (hunk 1 above)
Comment (wj331) [reply src/main/java/seedu/address/logic/parser/ViewAvailableCommandParser.java]: Thanks for the suggestion

DATE is fully capitalized because it is a parameter so I think it is fine to leave it fully capped

I think the format is fine also, could be good to let the user know the correct command after he inserts something wrong as seen
image

**Review by simbayippy — APPROVED** [review]
lgtm
